"""
AI Assistant Pydantic schemas.

Only defines the shapes that cross the HTTP boundary.
Never touches existing inventory schemas.
"""

from typing import Any

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Incoming chat message from the frontend."""
    message: str = Field(..., min_length=1, max_length=2000, description="User's natural language question")
    language: str = Field(
        default="en",
        pattern="^(en|fr)$",
        description="UI language code ('en' or 'fr'), mirrors the app's existing LanguageContext. Determines the language of the assistant's answer.",
    )


class ChatResponse(BaseModel):
    """Response returned to the frontend after running the AI pipeline."""
    answer: str = Field(..., description="Natural language answer generated by the LLM")
    sql: str | None = Field(None, description="The SELECT query that was executed (for transparency)")
    rows: list[Any] | None = Field(None, description="Raw result rows (up to MAX_ROWS)")
    error: str | None = Field(None, description="Human-readable error message if something went wrong")