"""
Utilities Package

Contains utility functions for validation, helpers, and common operations.
"""

# Import all validators
# Import all helpers
from src.utils.helpers import (
    PaginatedResponse,
    PaginationParams,
    calculate_days_between,
    calculate_total_pages,
    chunk_list,
    clamp,
    days_until_due,
    deduplicate_list,
    dict_to_csv,
    flatten_dict,
    format_datetime,
    format_duration,
    format_file_size,
    generate_filename,
    generate_hash,
    generate_report_filename,
    generate_unique_id,
    get_date_range,
    group_by,
    is_overdue,
    paginate_query,
    percentage,
    read_csv_to_dict,
    safe_get,
    slugify,
    title_case,
    truncate_string,
)
from src.utils.validators import (
    calculate_password_strength,
    generate_item_code,
    is_company_email,
    is_safe_string,
    normalize_phone,
    sanitize_filename,
    sanitize_string,
    validate_date_string,
    validate_email,
    validate_file_extension,
    validate_file_size,
    validate_item_code,
    validate_password,
    validate_phone,
    validate_positive_integer,
    validate_qr_code_data,
    validate_quantity,
    validate_url,
)

__all__ = [
    "PaginatedResponse",
    "PaginationParams",
    "calculate_days_between",
    "calculate_password_strength",
    "calculate_total_pages",
    "chunk_list",
    "clamp",
    "days_until_due",
    "deduplicate_list",
    "dict_to_csv",
    "flatten_dict",
    "format_datetime",
    "format_duration",
    "format_file_size",
    "generate_filename",
    "generate_hash",
    "generate_item_code",
    "generate_report_filename",
    "generate_unique_id",
    "get_date_range",
    "group_by",
    "is_company_email",
    "is_overdue",
    "is_safe_string",
    "normalize_phone",
    "paginate_query",
    "percentage",
    "read_csv_to_dict",
    "safe_get",
    "sanitize_filename",
    "sanitize_string",
    "slugify",
    "title_case",
    "truncate_string",
    "validate_date_string",
    "validate_email",
    "validate_file_extension",
    "validate_file_size",
    "validate_item_code",
    "validate_password",
    "validate_phone",
    "validate_positive_integer",
    "validate_qr_code_data",
    "validate_quantity",
    "validate_url",
]